
# mkskel.cmake - CMake function to generate C files from skeleton files
# 
# Usage: mkskel_generate_c(OUTPUT_FILE skeleton_file1 skeleton_file2 ...)
#
# This function converts skeleton files into a C source file containing
# string literals and a lookup table, equivalent to the mkskel-sh script.
# Copyright (C) 2002  Southern Storm Software, Pty Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

function(mkskel_generate_c OUTPUT_FILE)
    set(INPUT_FILES ${ARGN})

    if(NOT INPUT_FILES)
        message(FATAL_ERROR "mkskel_generate_c() requires at least one input file.")
    endif()

    set(HEADER "/* This file is automatically generated by CMake - do not edit */\n\n#include \"config.h\"\n\n")
    file(WRITE ${OUTPUT_FILE} "${HEADER}")

    set(LOOKUP_TABLE_ENTRIES "")

    foreach(SKELETON_FILE ${INPUT_FILES})
        get_filename_component(BASENAME ${SKELETON_FILE} NAME)

        string(REPLACE "." "_" VARNAME_SUFFIX ${BASENAME})
        set(VARNAME "TreeCCSkel_${VARNAME_SUFFIX}")

        file(READ "${SKELETON_FILE}" FILE_CONTENT ENCODING UTF-8)

        string(REPLACE "\\" "\\\\" FILE_CONTENT_ESCAPED "${FILE_CONTENT}")
        string(REPLACE "\"" "\\\"" FILE_CONTENT_ESCAPED "${FILE_CONTENT_ESCAPED}")
        string(REPLACE "\n" "\\n\"\n\"" FILE_CONTENT_ESCAPED "${FILE_CONTENT_ESCAPED}")

        file(APPEND ${OUTPUT_FILE} "static char const ${VARNAME}[] = \"${FILE_CONTENT_ESCAPED}\";\n\n")

        list(APPEND LOOKUP_TABLE_ENTRIES "    \"${BASENAME}\", ${VARNAME},")
    endforeach()

    list(JOIN LOOKUP_TABLE_ENTRIES "\n" LOOKUP_TABLE_STRING)

    file(APPEND ${OUTPUT_FILE} "const char * const TreeCCSkelFiles[] = {\n")
    file(APPEND ${OUTPUT_FILE} "${LOOKUP_TABLE_STRING}\n")
    file(APPEND ${OUTPUT_FILE} "    0\n};\n")
endfunction()